config/routes.rb
OdinFlightBooker::Application.routes.draw do
  resources :flights,  only: [:index]
  resources :bookings, only: [:new, :create,:show]
  
  root 'flights#index'

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, :foreign_key => "departure_id", :class_name => "Flight"
  has_many :arriving_flights,  :foreign_key => "arrival_id",   :class_name => "Flight"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many :passengers
  belongs_to :flight

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :to_airport,   :foreign_key => 'arrival_id', :class_name => "Airport"
  belongs_to :from_airport, :foreign_key => 'departure_id',:class_name => "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
 

  def self.get_dates
    pluck(:date).map{ |d| [ d.strftime("%m/%d/%Y")] }.uniq
  end
  # need a better check here.
  def self.get_flights(params)
    if !params[:date].nil?
      date = params[:date].to_date
      Flight.where(departure_id: params[:from_airport], arrival_id: params[:to_airport],
                  date: date.beginning_of_day..date.end_of_day)
                  .includes(:from_airport, :to_airport)
    end
 end

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
  has_many :flights, through: :bookings

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @flight = Flight.find(params[:flight])
    @booking = Booking.new
    params[:passengers].to_i.times{@booking.passengers.build}
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |p|
        PassengerMailer.welcome_email(p).deliver
      end
      flash[:success] = "Booking Complete!"
      redirect_to @booking
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
                                    passengers_attributes: [:name, :email] )
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @airports = Airport.all.map{|a| [a.airport_code, a.id]} 
    @passengers = 4.times.map{|n| [n + 1]}
    @dates = Flight.get_dates
    @flights = Flight.get_flights(flight_params)
  end

  private

    def flight_params
      params.permit(:to_airport,:from_airport,:date, :passengers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_form.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @booking,  :html => {:class => "form-horizontal", :role => "form"} do |f| %>
			<fieldset>
				<legend>Passengers</legend>
				<%= f.hidden_field :flight_id, :value => @flight.id%>	
				<%= f.fields_for :passengers do |p| %>
					<div class="form-group">
						<%= p.label(:name) %>
						<%= p.text_field(:name) %>
						<%= p.label(:email) %>
						<%= p.email_field(:email) %>
					</div>
			  	<% end %>
			  	<%= submit_tag "Submit" %>
			 </fieldset>
		<% end %>
	</div>
</div>

app/views/bookings/_display.html.erb
<h2>Flight # <strong><%= o.id %></strong> 
leaving <strong><%= o.from_airport.airport_code %></strong> 
for <strong><%= o.to_airport.airport_code %></strong> 
at <strong><%= o.date.strftime("%I:%M%p") %></strong> 
on <strong><%= o.date.strftime("%B %d, %Y") %></strong></h2>

app/views/bookings/new.html.erb
<h1><strong>Booking</strong></h1>
<%= render 'display', o: @flight%>

<%= render 'booking_form' %>

app/views/bookings/show.html.erb
<h1><strong>Booking Confirmation</strong></h2>

<%= render 'display', o: @booking.flight %>

<h4><strong>Passengers</strong></h4>

<% @booking.passengers.each do |p| %>
		<p> <%="#{p.name}" %></p>
<% end %>

<i><h5>Confirmation number: <%= @booking.id %></h5></i>

app/views/flights/_flight_form.html.erb
<div class="col-md-8 col-md-offset-3" id="flights" >
	<%= form_tag(new_booking_path, method: "get") do %>
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Select</th>
					<th>Flight #</th>
					<th>Date</th>
					<th>Departing</th>
					<th>Arriving</th>
					<th>Time</th>
					<th>Duration</th>
				</tr>
			</thead>
			<tbody>
				<% @flights.each do |f| %>
					<tr>
						<td><%= radio_button_tag(:flight, f.id) %></td>
						<td><%= f.id %></td>
						<td><%= f.date.strftime("%B %d, %Y") %></td>	
						<td><%= f.from_airport.airport_code %></td>	
						<td><%= f.to_airport.airport_code %></td>
						<td><%= f.date.strftime("%I:%M%p") %></td>
						<td><%= f.duration %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<%= hidden_field_tag(:passengers, params[:passengers]) %>
		<%= submit_tag "Submit" %>
	<% end %>
</div>

app/views/flights/_search_form.html.erb
<div class="col-md-8 col-md-offset-3">
	<div class="form-group">
		<%= form_tag("/flights", method: "get") do %>

			<%= label_tag(:from_airport, 'Departing') %>
			<%= select_tag(:from_airport, options_for_select(@airports)) %>

			<%= label_tag(:to_airport, 'Arriving') %>
			<%= select_tag(:to_airport, options_for_select(@airports)) %>

			<%= label_tag(:date, 'Date') %>
			<%= select_tag(:date, options_for_select(@dates)) %>

			<%= label_tag(:passengers, 'Passengers') %>
			<%= select_tag(:passengers, options_for_select(@passengers)) %>

			<%= submit_tag("Search") %>

		<% end %>
	</div>
</div>

app/views/flights/index.html.erb
<%= render 'search_form' %>

<% if !@flights.nil? %>
<%= render 'flight_form' %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<%= link_to "FlightBooker", root_url, id: "logo" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	    <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>